CREATE TABLE IF NOT EXISTS FILES (
    ID VARCHAR PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    FILE_UNIQUE_ID VARCHAR NOT NULL,
    FILE_ID VARCHAR NOT NULL,
    TAGS VARCHAR,
    DATETIME TIMESTAMP NOT NULL
)