CREATE TABLE IF NOT EXISTS FILES (
    ID VARCHAR PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    FILE_UNIQUE_ID VARCHAR NOT NULL,
    FILE_ID VARCHAR NOT NULL,
    FILE_TYPE VARCHAR NOT NULL,
    TAGS VARCHAR,
    DATETIME TIMESTAMP NOT NULL
);

CREATE ALIAS IF NOT EXISTS FTL_INIT FOR "org.h2.fulltext.FullTextLucene.init";
CALL FTL_INIT();
CALL FTL_CREATE_INDEX('PUBLIC', 'FILES', 'TAGS');